name: Update repo list 
on: 
  workflow_dispatch:

jobs:
  create-and-commit-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Fetch Repositories and Create Markdown List
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'xxradar'
        git config --global user.email 'xxradar@radarhack.com'
        page=1
        repos=()

        while true; do
          # Fetch repositories from organization
          response=$(curl -s -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/orgs/kubiosec-ai/repos?per_page=100&page=$page")
          
          # Break loop if no more results
          if [ "$(echo "$response" | jq '. | length')" -eq 0 ]; then
            break
          fi

          # Filter repositories to include only non-forked repos (both public and private)
          page_repos=$(echo "$response" | jq -r '.[] | select(.fork == false) | .full_name')
          repos+=($page_repos)
          page=$((page + 1))
        done

        # Create or clear the file
        > list.md

        # Write repository links to file
        for i in "${repos[@]}"
        do
          echo "- [https://github.com/${i}](https://github.com/${i})" >> list.md
        done

        # Commit and push changes if there are updates
        if ! git diff --quiet; then
          git add list.md
          git commit -m "Update repository list"
          git push
        else
          echo "No changes in repository list"
        fi
